Add usefull options to some blocs
umanit/block-collection-bundle pull request #2
Opened 2020-08-03 10:14 UTC by Wanere

Add several fields in blocks :
- FaqQuestion block : file, buttonText (for download the file), image and alt
- Quote block : Image, Alt and Role
- Tryptich block : imagePosition (for front)

2020-08-05 16:03 UTC, DjLeChuck requested changes

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/FaqQuestion.php
> +    private $file;
* Il manque le type `@var string`
* Le champ doit être `nullable`
* Gardons la logique de l'existant avec les images, donc `filePath`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/FaqQuestion.php
> +    private $buttonText;
* Renommer en `fileButtonPath`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/FaqQuestion.php
> +    private $image;
`imagePath`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/FaqQuestion.php
> +    private $alt;
`imageAlt`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/FaqQuestion.php
> +    private $alt;
Et il manque tous les accesseurs.

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/Quote.php
> +    private $image;
* `imagePath`
* Pas de `length` max

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/Quote.php
> +    private $alt;
`imageAlt`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/Quote.php
> +    private $alt;
Pense à modifier la vue Twig par défaut pour ajouter ces nouveaux champs.
Attention à bien mettre des conditions si les données sont optionnelles.

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/Triptych.php
> +     * @ORM\Column(type="boolean", nullable=true)
Soit c'est le nom qui n'est pas parlant, soit le type `boolean` n'est pas correct.

`imagePosition` sous-entend qu'on va définir l'endroit où doit se placer l'image (en haut, en bas, à gauche, à droite ?) alors qu'avoir un booléen sous-entend un choix entre 2 positions seulement donc par exemple `imagePositionLeft`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Entity/Block/Triptych.php
> +     * @ORM\Column(type="boolean", nullable=true)
Même chose que pour l'autre bloc, penser à modifier la vue Twig pour refléter cette nouvelle possibilitée

2020-08-05 16:03 UTC, DjLeChuck commented on src/Form/Type/Block/FaqQuestionType.php
> +                'readonly' => true,
* Pourquoi l'option `readonly` ?
* Il manque le `'required' => false`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Form/Type/Block/FaqQuestionType.php
> +                'readonly' => true,
* Pourquoi l'option `readonly` ?
* Il manque le `'required' => false`

2020-08-05 16:03 UTC, DjLeChuck commented on src/Form/Type/Block/QuoteType.php
> +            ])
* Pourquoi l'option `readonly` ?

2020-09-07 16:11 UTC, Wanere commented on src/Form/Type/Block/FaqQuestionType.php
> +                'readonly' => true,
`readonly` c'est pour qu'on puisse pas modifier le path a la main, mais uniquement via Artgris !

2020-09-08 14:13 UTC, DjLeChuck requested changes
Pense à modifier la vue Twig par défaut pour ajouter ces nouveaux champs.
Attention à bien mettre des conditions si les données sont optionnelles.

2020-09-08 14:13 UTC, DjLeChuck commented on src/Entity/Block/FaqQuestion.php
> +     * @ORM\Column(type="string", nullable=true, length=255)
Pas de `length` max

2020-09-08 14:13 UTC, DjLeChuck commented on src/Entity/Block/Quote.php
> +    public function getImage(): ?string
Tu n'a pas adapté les noms / retours des accesseurs au changement de nom de la propriété

2020-09-08 14:42 UTC, DjLeChuck approved these changes

2020-09-08 14:43 UTC, merged

2020-09-08 14:43 UTC, DjLeChuck commented
Merci 👍